
# Módulo 3: Procesamiento de datos con Python

## Abrir achivo csv

Archivos a utilizar:
- [productos-verano-calificación-rendimiento_2020-08](../DS/productos-verano-calificación-rendimiento_2020-08.csv) 
- [categorias-unicas](../DS/categorias-unicas.csv) 
- [categorias-unicas-ordenadas-recuento](../DS/categorias-unicas-ordenadas-recuento.csv) 

Se requiere la instalación de pandas `!pip install pandas`

In [96]:
import pandas as pd
df = pd.read_csv('../DS/productos-verano-calificación-rendimiento_2020-08.csv')
df

,titulo_original,Titulo_corto,precio,precio_al_por_menor,comprador_de_divisas,unidades_vendidas,utiliza_refuerzos_publicitarios,clasificacion,conteo_de_calificacion,calificacion_cinco_cuenta,...,conteo_de_calificaciones_del_comerciante,calificacion_del_comerciante,comerciante_id,el_comerciante_tiene_una_foto_de_perfil,foto_de_perfil_del_comerciante,URL_del_producto,imagen_del_producto,ID_del_producto,tema,mes_de_rastreo
0,2020 Summer Vintage Flamingo Print Pajamas Se...,2020 Summer Vintage Flamingo Print Paja,16.00,14,EUR,100,0,3.76,54,26.0,...,568,4.128521,595097d6a26f6e070cb878d1,0,NaN,https://www.wish.com/c/5e9ae51d43d6a96e303acdb0,https://contestimg.wish.com/api/webimage/5e9ae...,5e9ae51d43d6a96e303acdb0,summer,2020-08
1,Women's Casual Summer Sleeveless Sexy Mini Dress,Women's Casual Summer Sleeveless Sexy Mi,8.00,22,EUR,20000,1,3.45,6135,2269.0,...,17752,3.899673,56458aa03a698c35c9050988,0,NaN,https://www.wish.com/c/58940d436a0d3d5da4e95a38,https://contestimg.wish.com/api/webimage/58940...,58940d436a0d3d5da4e95a38,summer,2020-08
2,2020 New Arrival Women Spring and Summer Beach...,2020 New Arrival Women Spring and Summer,8.00,43,EUR,100,0,3.57,14,5.0,...,295,3.989831,5d464a1ffdf7bc44ee933c65,0,NaN,https://www.wish.com/c/5ea10e2c617580260d55310a,https://contestimg.wish.com/api/webimage/5ea10...,5ea10e2c617580260d55310a,summer,2020-08
3,Hot Summer Cool T Shirt for Women Fashion Tops...,Hot Summer Cool T Shirt for Women Fashio,8.00,8,EUR,5000,1,4.03,579,295.0,...,23832,4.020435,58cfdefdacb37b556efdff7c,0,NaN,https://www.wish.com/c/5cedf17ad1d44c52c59e4aca,https://contestimg.wish.com/api/webimage/5cedf...,5cedf17ad1d44c52c59e4aca,summer,2020-08
4,Women Summer Shorts Lace Up Elastic Waistband ...,Women Summer Shorts Lace Up Elastic Wais,2.72,3,EUR,100,1,3.10,20,6.0,...,14482,4.001588,5ab3b592c3911a095ad5dadb,0,NaN,https://www.wish.com/c/5ebf5819ebac372b070b0e70,https://contestimg.wish.com/api/webimage/5ebf5...,5ebf5819ebac372b070b0e70,summer,2020-08
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1568,New Fashion Women Bohemia Dandelion Print Tee ...,New Fashion Women Bohemia Dandelion Prin,6.00,9,EUR,10000,1,4.08,1367,722.0,...,5316,4.224605,5b507899ab577736508a0782,0,NaN,https://www.wish.com/c/5d5fadc99febd9356cbc52ee,https://contestimg.wish.com/api/webimage/5d5fa...,5d5fadc99febd9356cbc52ee,summer,2020-08
1569,10 Color Women Summer Shorts Lace Up Elastic W...,10 Color Women Summer Shorts Lace Up Ela,2.00,56,EUR,100,1,3.07,28,11.0,...,4435,3.696054,54d83b6b6b8a771e478558de,0,NaN,https://www.wish.com/c/5eccd22b4497b86fd48f16b4,https://contestimg.wish.com/api/webimage/5eccd...,5eccd22b4497b86fd48f16b4,summer,2020-08
1570,New Men Siwmwear Beach-Shorts Men Summer Quick...,New Men Siwmwear Beach-Shorts Men Summer,5.00,19,EUR,100,0,3.71,59,24.0,...,210,3.961905,5b42da1bf64320209fc8da69,0,NaN,https://www.wish.com/c/5e74be96034d613d42b52dfe,https://contestimg.wish.com/api/webimage/5e74b...,5e74be96034d613d42b52dfe,summer,2020-08
1571,Fashion Women Summer Sleeveless Dresses V Neck...,Fashion Women Summer Sleeveless Dresses,13.00,11,EUR,100,0,2.50,2,0.0,...,31,3.774194,5d56b32c40defd78043d5af9,0,NaN,https://www.wish.com/c/5eda07ab0e295c2097c36590,https://contestimg.wish.com/api/webimage/5eda0...,5eda07ab0e295c2097c36590,summer,2020-08
1572,Fashion Women Yoga Pants Slim Fit Fitness Runn...,Fashion Women Yoga Pants Slim Fit Fitnes,7.00,6,EUR,100,1,4.07,14,8.0,...,7023,4.235939,5a409cf87b584e7951b2e25f,0,NaN,https://www.wish.com/c/5e857321f53c3d2d8f25e7ed,https://contestimg.wish.com/api/webimage/5e857...,5e857321f53c3d2d8f25e7ed,summer,2020-08

 ## Conexión directa con Mongo DB

Se requiere la instalación de pandas `!pip install pymongo`

Para este ejemplo se conectara a servidor local, base de datos **Proyecto2**

In [76]:
from pymongo import MongoClient
from bson.json_util import dumps, loads

client = pymongo.MongoClient('localhost',27017)
#Lista bases de datos de servidor
client.list_database_names()

['admin', 'config', 'local', 'proyecto', 'proyecto2']

In [81]:
#Utilizar base de datos proyecto2
db = client['proyecto2']
#Coleciones
db.list_collection_names()

['categorias', 'ventas']

In [82]:
collection = db['ventas']
#Numero de documentos
collection.count_documents({})

4704

In [118]:
#Ver informacion de cursor 
info = collection.find()
#for cr in info:
#    print(cr)

In [117]:
#Convertir cursor a Json
cursor = collection.find()
list_cur = list(cursor)
json_data = dumps(list_cur)
#json_data

In [119]:
#Convertir cursor a Dataframe
df = pd.DataFrame(list_cur)
df

,_id,Periodo,TipoProducto,Region,Ingresos,Gastos
0,625f328e5e80e0def19c042e,Q1 2019,Accesorios,AGO - Africa/Angola,66319.703780,56708.152510
1,625f328e5e80e0def19c042f,Q1 2019,Aplicaciones,AGO - Africa/Angola,122357.282900,77039.770740
2,625f328e5e80e0def19c0430,Q1 2019,Celulares,AGO - Africa/Angola,265278.815100,215226.208500
3,625f328e5e80e0def19c0431,Q1 2019,Musica,AGO - Africa/Angola,130447.020700,86964.680440
4,625f328e5e80e0def19c0432,Q1 2019,PC,AGO - Africa/Angola,394602.237500,326567.369000
...,...,...,...,...,...,...
4699,625f328e5e80e0def19c1689,Q4 2021,Celulares,NZL - Oceania/Nueva Zelanda,47516.938980,41006.107340
4700,625f328e5e80e0def19c168a,Q4 2021,Musica,NZL - Oceania/Nueva Zelanda,26290.625230,15057.358080
4701,625f328e5e80e0def19c168b,Q4 2021,PC,NZL - Oceania/Nueva Zelanda,99027.767440,83854.981130
4702,625f328e5e80e0def19c168c,Q4 2021,Tablets,NZL - Oceania/Nueva Zelanda,16346.893050,13292.605140
4703,625f328e5e80e0def19c168d,Q4 2021,TV,NZL - Oceania/Nueva Zelanda,6571.491561,4343.310186

## Conexión API local 

Se requiere la instalación de `!pip install requests`

Para este ejemplo se conectara a servidor local, base de datos **http://localhost:3000/api/craigslists**

In [127]:
import requests
endpoint = 'http://localhost:3000/api/craigslists'
r = requests.get(endpoint)

In [128]:
r.json().keys()

dict_keys(['ok', 'craigslist'])

In [129]:
json = r.json()
result = json['craigslist']

> Convertir resultado obtenido en el API a Dataframe

In [130]:
normalized = pd.json_normalize(result)

df = pd.DataFrame.from_dict(normalized)

df.head()

,_id,id,url,region,region_url,precio,anio,fabricante,modelo,condicion,...,tipo,color,imagen_url,descripcion,estado,lat,long,fechapublicacion,manejo,tamanio
0,625f16695e80e0def195806a,7316814884,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,33590,2014,gmc,sierra 1500 crew cab slt,good,...,pickup,white,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04T17:31:18.000Z,NaN,NaN
1,625f16695e80e0def195806b,7316814758,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,22590,2010,chevrolet,silverado 1500,good,...,pickup,blue,https://images.craigslist.org/00R0R_lwWjXSEWNa...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04T17:31:08.000Z,NaN,NaN
2,625f16695e80e0def195806c,7316814989,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,39590,2020,chevrolet,silverado 1500 crew,good,...,pickup,red,https://images.craigslist.org/01212_jjirIWa0y0...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04T17:31:25.000Z,NaN,NaN
3,625f16695e80e0def195806d,7316743432,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,30990,2017,toyota,tundra double cab sr,good,...,pickup,red,https://images.craigslist.org/00x0x_1y9kIOzGCF...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-04T15:41:31.000Z,NaN,NaN
4,625f16695e80e0def195806e,7316356412,https://auburn.craigslist.org/cto/d/auburn-uni...,auburn,https://auburn.craigslist.org,15000,2013,ford,f-150 xlt,excellent,...,truck,black,https://images.craigslist.org/00404_l4loxHvdQe...,2013 F-150 XLT V6 4 Door. Good condition. Leve...,al,32.592,-85.5189,2021-05-03T19:02:03.000Z,rwd,full-size

> Es posible acceder a esta información leyendo la propiedad shape de nuestro DataFrame mostrando numero de registros y columnas:

In [137]:
df.shape

(2000, 20)

In [131]:
#Trae registro especifico
df.loc[5]

_id                                          625f16695e80e0def195806f
id                                                         7316343444
url                 https://auburn.craigslist.org/ctd/d/auburn-uni...
region                                                         auburn
region_url                              https://auburn.craigslist.org
precio                                                          27990
anio                                                             2012
fabricante                                                        gmc
modelo                                    sierra 2500 hd extended cab
condicion                                                        good
cilindros                                                 8 cylinders
combustible                                                       gas
odometro                                                        68696
titulostatus                                                    clean
transmision                                                     other
VIN                                                 1GT220CG8CZ231238
tipo                                                           pickup
color                                                           black
imagen_url          https://images.craigslist.org/00V0V_ftJbKrOgdi...
descripcion         Carvana is the safer way to buy a car During t...
estado                                                             al
lat                                                             32.59
long                                                           -85.48
fechapublicacion                             2021-05-03T18:41:25.000Z
manejo                                                            4wd
tamanio                                                           NaN
Name: 5, dtype: object

In [135]:
#Trae un rango de registros especificos
df.loc[5:7]

,_id,id,url,region,region_url,precio,anio,fabricante,modelo,condicion,...,tipo,color,imagen_url,descripcion,estado,lat,long,fechapublicacion,manejo,tamanio
5,625f16695e80e0def195806f,7316343444,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,27990,2012,gmc,sierra 2500 hd extended cab,good,...,pickup,black,https://images.craigslist.org/00V0V_ftJbKrOgdi...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-03T18:41:25.000Z,4wd,NaN
6,625f16695e80e0def1958070,7316304717,https://auburn.craigslist.org/ctd/d/auburn-uni...,auburn,https://auburn.craigslist.org,34590,2016,chevrolet,silverado 1500 double,good,...,pickup,silver,https://images.craigslist.org/00E0E_iKN07Sh7ou...,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,2021-05-03T17:41:33.000Z,4wd,NaN
7,625f16695e80e0def1958071,7316285779,https://auburn.craigslist.org/cto/d/auburn-201...,auburn,https://auburn.craigslist.org,35000,2019,toyota,tacoma,excellent,...,truck,grey,https://images.craigslist.org/00101_dXoZTH7iVm...,Selling my 2019 Toyota Tacoma TRD Off Road Dou...,al,32.6013,-85.443974,2021-05-03T17:12:59.000Z,4wd,NaN

In [136]:
#Elimina columnas con informacion no relevante
df=df.drop(columns=['_id','id','url','region_url','imagen_url','fechapublicacion'])
#Primeras filas 
df.head()

,region,precio,anio,fabricante,modelo,condicion,cilindros,combustible,odometro,titulostatus,transmision,VIN,tipo,color,descripcion,estado,lat,long,manejo,tamanio
0,auburn,33590,2014,gmc,sierra 1500 crew cab slt,good,8 cylinders,gas,57923,clean,other,3GTP1VEC4EG551563,pickup,white,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,NaN,NaN
1,auburn,22590,2010,chevrolet,silverado 1500,good,8 cylinders,gas,71229,clean,other,1GCSCSE06AZ123805,pickup,blue,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,NaN,NaN
2,auburn,39590,2020,chevrolet,silverado 1500 crew,good,8 cylinders,gas,19160,clean,other,3GCPWCED5LG130317,pickup,red,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,NaN,NaN
3,auburn,30990,2017,toyota,tundra double cab sr,good,8 cylinders,gas,41124,clean,other,5TFRM5F17HX120972,pickup,red,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,NaN,NaN
4,auburn,15000,2013,ford,f-150 xlt,excellent,6 cylinders,gas,128000,clean,automatic,NaN,truck,black,2013 F-150 XLT V6 4 Door. Good condition. Leve...,al,32.592,-85.5189,rwd,full-size

In [139]:
#Ultimas Filas
df.tail()

,region,precio,anio,fabricante,modelo,condicion,cilindros,combustible,odometro,titulostatus,transmision,VIN,tipo,color,descripcion,estado,lat,long,manejo,tamanio
1995,dothan,11998,2014,hyundai,genesis coupe 2.0t,excellent,NaN,gas,101085,clean,automatic,KMHHT6KD9EU114345,NaN,blue,2014 Hyundai Genesis Coupe 2.0T - STOCK #: FPA...,al,31.796941,-85.980049,NaN,NaN
1996,dothan,4999,2006,nissan,pathfinder,NaN,6 cylinders,gas,138000,clean,automatic,NaN,NaN,NaN,Nice 2006 Nissan pathfinder. Run's and drives ...,al,31.4391,-85.6436,NaN,NaN
1997,dothan,7250,2012,chevrolet,sonic,good,4 cylinders,gas,122000,clean,manual,NaN,NaN,blue,🤱💐Mothers day is quickly approaching come see ...,al,31.086,-85.7192,NaN,NaN
1998,dothan,19998,2020,ford,escape s,excellent,NaN,gas,26561,clean,automatic,1FMCU0F67LUA59696,NaN,NaN,2020 Ford Escape S - STOCK #: FPD77811A Avail...,al,31.796941,-85.980049,NaN,NaN
1999,dothan,4000,2001,jeep,grand cherokee,fair,6 cylinders,gas,117000,clean,automatic,NaN,SUV,white,Up for sale is a 2001 Jeep Grand Cherokee runs...,al,31.369,-85.9404,rwd,mid-size

In [140]:
#La propiedad dtypes nos da una Serie donde podemos ver cada columna y el tipo de dato que contiene:
df.dtypes

region          object
precio          object
anio            object
fabricante      object
modelo          object
condicion       object
cilindros       object
combustible     object
odometro        object
titulostatus    object
transmision     object
VIN             object
tipo            object
color           object
descripcion     object
estado          object
lat             object
long            object
manejo          object
tamanio         object
dtype: object

In [144]:
#Contar cuántos NaNs existen usando la agregación sum, que suma 1 por cada True y 0 por cada False
df.isna().sum(axis=0)

region             0
precio             0
anio              22
fabricante       144
modelo            13
condicion        859
cilindros        730
combustible       34
odometro          12
titulostatus     103
transmision        1
VIN              719
tipo             607
color            452
descripcion        0
estado             0
lat               12
long              12
manejo           626
tamanio         1504
dtype: int64

In [145]:
#Con axis=0 nos regresa el conteo por columnas. Con axis=1 nos regresa el conteo por filas:
df.isna().sum(axis=1)

0       2
1       2
2       2
3       2
4       1
       ..
1995    4
1996    6
1997    4
1998    5
1999    1
Length: 2000, dtype: int64

Para limpiar las filas que tengan mínimo 1 valor NaN `df.dropna(axis=0, how='any')`
>Cambiar valores NAN por un valor

In [148]:
df['tamanio'] = df['tamanio'].fillna('sin tamanio')
df.head()

,region,precio,anio,fabricante,modelo,condicion,cilindros,combustible,odometro,titulostatus,transmision,VIN,tipo,color,descripcion,estado,lat,long,manejo,tamanio
0,auburn,33590,2014,gmc,sierra 1500 crew cab slt,good,8 cylinders,gas,57923,clean,other,3GTP1VEC4EG551563,pickup,white,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,NaN,sin tamanio
1,auburn,22590,2010,chevrolet,silverado 1500,good,8 cylinders,gas,71229,clean,other,1GCSCSE06AZ123805,pickup,blue,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,NaN,sin tamanio
2,auburn,39590,2020,chevrolet,silverado 1500 crew,good,8 cylinders,gas,19160,clean,other,3GCPWCED5LG130317,pickup,red,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,NaN,sin tamanio
3,auburn,30990,2017,toyota,tundra double cab sr,good,8 cylinders,gas,41124,clean,other,5TFRM5F17HX120972,pickup,red,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,NaN,sin tamanio
4,auburn,15000,2013,ford,f-150 xlt,excellent,6 cylinders,gas,128000,clean,automatic,NaN,truck,black,2013 F-150 XLT V6 4 Door. Good condition. Leve...,al,32.592,-85.5189,rwd,full-size

In [149]:
#Cambia el NAN en manejo por default awd
df['manejo'] = df['manejo'].fillna('awd')
df.head()

,region,precio,anio,fabricante,modelo,condicion,cilindros,combustible,odometro,titulostatus,transmision,VIN,tipo,color,descripcion,estado,lat,long,manejo,tamanio
0,auburn,33590,2014,gmc,sierra 1500 crew cab slt,good,8 cylinders,gas,57923,clean,other,3GTP1VEC4EG551563,pickup,white,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,awd,sin tamanio
1,auburn,22590,2010,chevrolet,silverado 1500,good,8 cylinders,gas,71229,clean,other,1GCSCSE06AZ123805,pickup,blue,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,awd,sin tamanio
2,auburn,39590,2020,chevrolet,silverado 1500 crew,good,8 cylinders,gas,19160,clean,other,3GCPWCED5LG130317,pickup,red,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,awd,sin tamanio
3,auburn,30990,2017,toyota,tundra double cab sr,good,8 cylinders,gas,41124,clean,other,5TFRM5F17HX120972,pickup,red,Carvana is the safer way to buy a car During t...,al,32.59,-85.48,awd,sin tamanio
4,auburn,15000,2013,ford,f-150 xlt,excellent,6 cylinders,gas,128000,clean,automatic,NaN,truck,black,2013 F-150 XLT V6 4 Door. Good condition. Leve...,al,32.592,-85.5189,rwd,full-size

In [153]:
df['precio'].min()

'0'

In [154]:
df['precio'].max()

'99999999'

In [155]:
df.sort_values('precio',ascending=false)

NameError: name 'false' is not defined